name: attendance
description: A new Flutter project.
publish_to: "none" # remove this line if you plan to publish

version: 1.0.0+1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # Updated dependencies (null safety + Dart 3 compatible)
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/login.png
    - assets/images/logo.png
    - assets/images/powered_by.png
    - assets/images/icon.png
